[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Renato Zannon <renato@rrsz.com.br>"]
edition = "2018"

[dependencies]
openssl = "0.10"
rand = "0.7"
percent-encoding = "2.1.0"
phf = { version = "0.8.0", features = ["macros"] }
colored = "1.9.3"

[workspace]
members = ["hmac-server"]
