[package]
name = "hmac-server"
version = "0.1.0"
authors = ["Renato Zannon <renato@rrsz.com.br>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros", "time"] }
warp = "0.2"
cryptopals = { path = ".." }
serde = "1.0"
serde_derive = "1.0"
rand = "0.7.3"
